version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0  # O usa la versión que necesites
    steps:
      - checkout  # Obtén el código del repositorio
      - run:
          name: Instalar dependencias
          command: dotnet restore  # Restaura las dependencias del proyecto
      - run:
          name: Construir la aplicación
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Ejecutar pruebas
          command: dotnet test --no-build --verbosity normal
      - run:
          name: Publicar "Hello World"
          command: echo "Hello from .NET Core API!"

workflows:
  build-and-test:
    jobs:
      - build
