version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Usamos una imagen de Node.js para React

    steps:
      - checkout  # Clona tu proyecto
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Ejecutar pruebas
          command: npm test -- --watchAll=false

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
