version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
      - run:
          command: npm run build
      - run:
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
